export default {
  PLATE: require("../../assets/images/plate.png"),
  DISCOVER: require("../../assets/images/discover.png"),
  DELIVER: require("../../assets/images/deliver.png"),
  FAVORITE: require("../../assets/images/favorite.png"),
  FACEBOOK: require("../../assets/images/facebook.png"),
  GOOGLE: require("../../assets/images/google.png"),
  PHONE: require("../../assets/images/phone.png"),
  FRIED_CHICKEN: require("../../assets/images/fried_chicken.png"),
  BURGER: require("../../assets/images/burger.png"),
  PIZZA: require("../../assets/images/pizza.png"),
  DESSERT: require("../../assets/images/dessert.png"),
  NOODLES: require("../../assets/images/noodles.png"),
  DRINKS: require("../../assets/images/drinks.png"),
  MCDONAL: require("../../assets/images//mcdonal.png"),
};
